# Generated by Django 5.1.7 on 2025-03-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_from_app',
            field=models.BooleanField(default=False),
        ),
    ]
