# Generated by Django 5.1.7 on 2025-06-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_created_from_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='Hello, I am using the Destination Experience App.', null=True),
        ),
    ]
