# Generated by Django 5.1.7 on 2025-06-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_notification_email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_notification_phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
