# Generated by Django 5.1.7 on 2025-07-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_preferred_notification_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_notification_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
