# Generated by Django 5.1.7 on 2025-03-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='hotels/')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('third_image', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('category', models.CharField(choices=[('STANDARD', 'Standard'), ('SHORTSTAY', 'Short Stay'), ('FAMILY', 'Family'), ('BOOTIQUE', 'Bootique')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Political',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('landmark', models.CharField(max_length=255)),
                ('custodian', models.URLField()),
                ('category', models.CharField(choices=[('MINISTRY', 'Ministry'), ('DEPARTMENT', 'Department'), ('AGENCY', 'Agency'), ('OTHERS', 'Others')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='political/')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='political/')),
                ('third_image', models.ImageField(blank=True, null=True, upload_to='political/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TouristSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('landmark', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='tourism/')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='tourism/')),
                ('third_image', models.ImageField(blank=True, null=True, upload_to='tourism/')),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
