# Generated by Django 5.1.7 on 2025-03-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='political',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='political/'),
        ),
        migrations.AlterField(
            model_name='touristsite',
            name='category',
            field=models.CharField(choices=[('HISTORICAL', 'Historical'), ('CULTURAL', 'Cultural'), ('LEISURE', 'Leisure'), ('NATURE', 'Nature'), ('ENTERTAINMENT', 'Entertainment'), ('OTHERS', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='touristsite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tourism/'),
        ),
    ]
