# Generated by Django 5.1.7 on 2025-03-14 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_political_image_alter_touristsite_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='political',
            name='custodian',
            field=models.CharField(max_length=200),
        ),
    ]
