# Generated by Django 5.1.7 on 2025-06-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_blog_is_published_alter_blog_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
