# Generated by Django 5.1.7 on 2025-06-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_blog_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(default='', max_length=250),
        ),
    ]
