# Generated by Django 5.1.7 on 2025-06-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_alter_blog_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristsite',
            name='custodian',
            field=models.CharField(default='No Custodian Identified', max_length=200),
        ),
    ]
