# Generated by Django 5.1.7 on 2025-06-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_chatroom_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='category',
            field=models.CharField(default='Standard', max_length=50),
        ),
    ]
