# Generated by Django 5.1.7 on 2025-06-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_alter_hotel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='political',
            name='category',
            field=models.CharField(default='Others', max_length=50),
        ),
        migrations.AlterField(
            model_name='touristsite',
            name='category',
            field=models.CharField(default='Others', max_length=50),
        ),
    ]
