# Generated by Django 5.1.7 on 2025-06-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_alter_political_category_alter_touristsite_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
