# Generated by Django 5.1.7 on 2025-07-18 01:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default=uuid.uuid4, max_length=200),
        ),
    ]
