# Generated by Django 5.1.7 on 2025-07-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_chatroom_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
