# Generated by Django 5.1.7 on 2025-07-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_alter_chatroom_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
